
// Example 3-1: guess number. 

// Input your guessed integer (assumed to be within 1~100), compare it with the number generated by the computer. If they are equal, display "guessed correctly"; if not, display the relationship between the guessed number and the generated number.

#include <stdio.h>
int main(void)
{
    int mynumber = 38; 
    int yournumber;

    printf("Input your number: "); 
    scanf("%d", &yournumber);

    if (yournumber == mynumber)
    { 
        printf("Good Guess!\n");
    }
    else if (yournumber > mynumber)
    {
        printf("Too big!\n");
    }
    else
    {
        printf("Too small!\n");
    }

    return 0;
}

// Input your number: 48
// Too big!

// Input your number: 38
// Good Guess!