
// Example 4-6-2: Guessing Game. Improve the simple guessing game in Example 3-1.
// Input the positive integer you guessed (assumed to be between 1 and 100) and compare it with the number generated by the computer. If they are equal, display "guessed right"; if not, display the relationship between the guessed number and the generated number. You are allowed to guess a maximum of 7 times.

#include <stdio.h>
#include <stdlib.h>
#include <time.h>

int main(void)
{
    int count = 0, flag, mynumber, yournumber;

    printf("Enter my number: ");
    scanf("%d", &mynumber);
    flag = 0;
    while (count < 7)
    {
        printf("Enter your number: ");
        scanf("%d", &yournumber);
        count++;
        if (yournumber == mynumber)
        {
            printf("Lucky You!\n");
            flag = 1;
            break;
        }
        else if (yournumber > mynumber)
        {
            printf("Too big\n");
        }
        else
        {
            printf("Too small\n");
        }
    }
    if (flag == 0)
    {
        printf("Game Over!\n");
    }

    return 0;
}

// Enter your number: 50
// Too big
// Enter your number: 25
// Too big
// Enter your number: 12
// Too small
// Enter your number: 18
// Too big
// Enter your number: 15
// Too big
// Enter your number: 13
// Too small
// Enter your number: 14
// Lucky You!